# Generated by Django 3.2.11 on 2022-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='statics/assets/img/author-1.jpg', max_length=255, upload_to=''),
        ),
    ]
