# Generated by Django 3.2.11 on 2022-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='statics/assets/img/post-1.jpg', max_length=255, upload_to=''),
        ),
    ]
